# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_rom_1/image_rom_1.xci
# IP: The module: 'image_rom_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_rom_1/image_rom_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_rom_1/image_rom_1.xci
# IP: The module: 'image_rom_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_rom_1/image_rom_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
